project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  page-navigation: true
  title: "MUSA 695"
  page-footer:
    left: "lumx@upenn.edu"
    right: 'This page is built with 🐤 and [Quarto](https://quarto.org/).'
    background: "#FAF4EC"

  sidebar:
    background: "#FAF4EC"
    logo: "images/Stitch icon.png"
    pinned: true
    align: center
    tools:
      - icon: person-fill
        href: https://storymaps.arcgis.com/stories/2f194999660c4b699a11bbb040190d93
        text: "Luming's Portfolio"
      - icon: github
        href: https://github.com/Bluebird-hi
        text: "Luming's GitHub"
      - icon: linkedin
        href: https://www.linkedin.com/in/luming-xu/
        text: "Luming's Linkedin"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: 1-index.qmd
        text: About Page
      - section: Reproducible Analysis
        contents:
          - 1.data-preparation.ipynb
          - 2.model-training.ipynb
          - 3.PLOT.ipynb
      - section: Appendix
        contents:
          - href: FinalPresentation_LumingXu.pdf
            text: Final Presentation
          - href: naip-studyarea.ipynb
            text: NAIP Preparation
          

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual
